#!/usr/bin/env python3
"""Generate modular HELIOS package and dependency documentation."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "packages" / "manifest.json"
SOURCE_MAP = ROOT / "docs" / "SOURCE_MAP.md"
DEPENDENCY_TREE = ROOT / "docs" / "DEPENDENCY_TREE.md"
DOFILE = re.compile(r'dofile\(\s*["\']/helios/(?P<path>[^"\']+\.lua)["\']\s*\)')


def load_files(manifest: dict) -> dict[str, dict]:
    files: dict[str, dict] = {}
    for package_id, package in manifest["packages"].items():
        for item in package["files"]:
            current = files.setdefault(item["path"], {
                "source": item["source"], "bytes": item["bytes"], "packages": []
            })
            if current["source"] != item["source"]:
                raise ValueError(f"conflicting sources for {item['path']}")
            current["packages"].append(package_id)
    return files


def render_source_map(manifest: dict, files: dict[str, dict]) -> str:
    installer_lines = len((ROOT / "install.lua").read_text(encoding="utf-8").splitlines())
    out = [
        "# HELIOS modular source map", "",
        "<!-- Generated by scripts/generate_source_map.py. -->", "",
        f"Core version: **{manifest['core_version']}**", "",
        f"The bootstrap `install.lua` is {installer_lines} readable lines and contains no runtime payload.",
        "It downloads only the packages selected for one computer from `packages/manifest.json`.", "",
        "## Packages", "",
    ]
    for package_id, package in manifest["packages"].items():
        size = sum(item["bytes"] for item in package["files"])
        requirements = ", ".join(f"`{item}`" for item in package["required"]) or "none"
        out.extend([
            f"### `{package_id}` — {package['name']}", "",
            f"- Kind: `{package['kind']}`", f"- Direct payload: {size} bytes",
            f"- Required packages: {requirements}", "",
        ])
        out.extend(f"- `{item['path']}` ← `{item['source']}` ({item['bytes']} bytes)" for item in package["files"])
        out.append("")
    out.extend(["## Shared destinations", ""])
    for path, metadata in sorted(files.items()):
        if len(metadata["packages"]) > 1:
            out.append(f"- `{path}`: " + ", ".join(f"`{item}`" for item in metadata["packages"]))
    out.append("")
    return "\n".join(out)


def render_dependencies(manifest: dict, files: dict[str, dict]) -> str:
    dependencies: dict[str, set[str]] = {path: set() for path in files}
    for installed, metadata in files.items():
        source = ROOT / metadata["source"]
        if source.suffix != ".lua":
            continue
        for match in DOFILE.finditer(source.read_text(encoding="utf-8")):
            dependency = match.group("path")
            if dependency in files and dependency != installed:
                dependencies[installed].add(dependency)
    reverse: dict[str, set[str]] = {path: set() for path in files}
    for user, requirements in dependencies.items():
        for requirement in requirements:
            reverse[requirement].add(user)
    out = [
        "# HELIOS modular dependency tree", "",
        "<!-- Generated by scripts/generate_source_map.py. -->", "",
        "Package dependencies are authoritative in `packages/manifest.json`; file dependencies below are inferred from installed `dofile` paths.", "",
        "## Package dependencies", "",
    ]
    for package_id, package in manifest["packages"].items():
        required = ", ".join(f"`{item}`" for item in package["required"]) or "none"
        out.append(f"- `{package_id}` → {required}")
    out.extend(["", "## File dependencies", ""])
    for path in sorted(files):
        required = ", ".join(f"`{item}`" for item in sorted(dependencies[path])) or "none detected"
        out.append(f"- `{path}` → {required}")
    out.extend(["", "## Reverse dependencies / blast radius", ""])
    for path in sorted(files):
        users = ", ".join(f"`{item}`" for item in sorted(reverse[path])) or "none detected"
        out.append(f"- `{path}` ← {users}")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    files = load_files(manifest)
    generated = {
        SOURCE_MAP: render_source_map(manifest, files),
        DEPENDENCY_TREE: render_dependencies(manifest, files),
    }
    stale = []
    for path, contents in generated.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != contents: stale.append(path)
        else:
            path.write_text(contents, encoding="utf-8");print(f"Wrote {path.relative_to(ROOT)}")
    if stale:
        print("Stale generated files: " + ", ".join(str(path.relative_to(ROOT)) for path in stale));return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
